import { useState } from 'react';
import { Download, FileText, FileSpreadsheet, Printer, Share2, MessageCircle, Copy, Check, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger, } from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';
export function BOQExportUtils({ boqData, roomName, totalAmount, formatCurrency, }) {
    const [exporting, setExporting] = useState(null);
    const [copied, setCopied] = useState(false);
    const handlePDFExport = async () => {
        setExporting('pdf');
        try {
            // Create printable HTML content
            const content = generatePrintableHTML();
            const printWindow = window.open('', '_blank');
            if (printWindow) {
                printWindow.document.write(content);
                printWindow.document.close();
                printWindow.onload = () => {
                    printWindow.print();
                };
            }
            toast.success('PDF export ready');
        }
        catch (error) {
            toast.error('Failed to generate PDF');
        }
        finally {
            setExporting(null);
        }
    };
    const handleExcelExport = () => {
        setExporting('excel');
        try {
            const csvContent = generateCSV();
            const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `houspire-boq-${roomName.toLowerCase().replace(/\s+/g, '-')}.csv`;
            a.click();
            URL.revokeObjectURL(url);
            toast.success('Excel/CSV downloaded');
        }
        catch (error) {
            toast.error('Failed to export');
        }
        finally {
            setExporting(null);
        }
    };
    const handlePrint = () => {
        window.print();
    };
    const handleWhatsAppShare = () => {
        const summary = generateSummaryText();
        const encodedText = encodeURIComponent(summary);
        window.open(`https://wa.me/?text=${encodedText}`, '_blank');
    };
    const handleCopyLink = async () => {
        await navigator.clipboard.writeText(window.location.href);
        setCopied(true);
        toast.success('Link copied!');
        setTimeout(() => setCopied(false), 2000);
    };
    const generatePrintableHTML = () => {
        return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Houspire BOQ - ${roomName}</title>
        <style>
          body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { color: #1a1a1a; border-bottom: 2px solid #eee; padding-bottom: 16px; }
          h2 { color: #666; margin-top: 32px; }
          table { width: 100%; border-collapse: collapse; margin: 16px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
          th { background: #f9f9f9; font-weight: 600; }
          .amount { text-align: right; }
          .total { font-size: 24px; font-weight: bold; margin-top: 32px; padding: 20px; background: #f0f9ff; border-radius: 8px; }
          .spec { color: #888; font-size: 12px; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #888; font-size: 12px; text-align: center; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>🏠 Houspire - Bill of Quantities</h1>
        <p><strong>Room:</strong> ${roomName}</p>
        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        
        ${boqData.map(cat => `
          <h2>${cat.name}</h2>
          <table>
            <thead>
              <tr>
                <th>Item</th>
                <th>Unit</th>
                <th>Qty</th>
                <th>Rate</th>
                <th class="amount">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${cat.items.map(item => `
                <tr>
                  <td>
                    ${item.name}
                    ${item.specification ? `<div class="spec">${item.specification}</div>` : ''}
                  </td>
                  <td>${item.unit}</td>
                  <td>${item.quantity}</td>
                  <td>${formatCurrency(item.rate)}</td>
                  <td class="amount">${formatCurrency(item.amount)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        `).join('')}
        
        <div class="total">
          Total Estimated Cost: ${formatCurrency(totalAmount)}
        </div>
        
        <div class="footer">
          Generated by Houspire • houspire.com • This is a sample estimate
        </div>
      </body>
      </html>
    `;
    };
    const generateCSV = () => {
        const headers = ['Category', 'Item', 'Specification', 'Unit', 'Quantity', 'Rate (INR)', 'Amount (INR)'];
        const rows = boqData.flatMap(cat => cat.items.map(item => [
            cat.name,
            item.name,
            item.specification || '',
            item.unit,
            item.quantity.toString(),
            item.rate.toString(),
            item.amount.toString(),
        ]));
        rows.push(['', '', '', '', '', 'TOTAL', totalAmount.toString()]);
        return [headers, ...rows]
            .map(row => row.map(cell => `"${cell}"`).join(','))
            .join('\n');
    };
    const generateSummaryText = () => {
        const categoryTotals = boqData.map(cat => {
            const total = cat.items.reduce((sum, item) => sum + item.amount, 0);
            return `• ${cat.name}: ${formatCurrency(total)}`;
        }).join('\n');
        return `🏠 *Houspire BOQ Estimate*\n\n` +
            `*Room:* ${roomName}\n\n` +
            `*Category Breakdown:*\n${categoryTotals}\n\n` +
            `*Total:* ${formatCurrency(totalAmount)}\n\n` +
            `View full details: ${window.location.href}`;
    };
    return (<div className="flex gap-2">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="gap-2">
            <Share2 className="h-4 w-4"/>
            <span className="hidden sm:inline">Share</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="bg-card">
          <DropdownMenuItem onClick={handleWhatsAppShare}>
            <MessageCircle className="h-4 w-4 mr-2 text-green-600"/>
            Share via WhatsApp
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleCopyLink}>
            {copied ? (<Check className="h-4 w-4 mr-2 text-green-600"/>) : (<Copy className="h-4 w-4 mr-2"/>)}
            Copy link
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button className="gap-2">
            {exporting ? (<Loader2 className="h-4 w-4 animate-spin"/>) : (<Download className="h-4 w-4"/>)}
            <span className="hidden sm:inline">Export</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="bg-card">
          <DropdownMenuItem onClick={handlePDFExport} disabled={!!exporting}>
            <FileText className="h-4 w-4 mr-2 text-red-600"/>
            Export as PDF
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleExcelExport} disabled={!!exporting}>
            <FileSpreadsheet className="h-4 w-4 mr-2 text-green-600"/>
            Export as Excel/CSV
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={handlePrint}>
            <Printer className="h-4 w-4 mr-2"/>
            Print
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>);
}
