import { useState } from 'react';
import { Share2, FileText, Link2, Check, MessageCircle, Heart, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger, } from '@/components/ui/dropdown-menu';
import { toast } from '@/hooks/use-toast';
export function MaterialExportUtils({ category, onAddToBOQ, onSaveFavorite, isFavorite = false }) {
    const [copied, setCopied] = useState(false);
    const [favorited, setFavorited] = useState(isFavorite);
    const generatePDF = () => {
        const content = `
<!DOCTYPE html>
<html>
<head>
  <title>${category.name} Material Guide - Houspire</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #e5e5e5; padding-bottom: 10px; }
    .tier { background: #f9f9f9; border-radius: 8px; padding: 20px; margin: 16px 0; }
    .tier-budget { border-left: 4px solid #E8662E; }
    .tier-standard { border-left: 4px solid #22c55e; }
    .tier-premium { border-left: 4px solid #f59e0b; }
    .tier h3 { margin: 0 0 10px 0; }
    .price { font-size: 1.1em; font-weight: 600; color: #059669; }
    .examples { color: #666; margin-top: 10px; }
    .rating { display: flex; gap: 4px; margin: 8px 0; }
    .star { color: #fbbf24; }
    .footer { margin-top: 40px; text-align: center; color: #888; font-size: 12px; }
  </style>
</head>
<body>
  <h1>📋 ${category.name} Material Guide</h1>
  <p>Compare quality tiers to make informed decisions for your interior project.</p>
  
  ${category.tiers.map(tier => `
    <div class="tier tier-${tier.name.toLowerCase()}">
      <h3>${tier.name}</h3>
      <p class="price">${tier.priceRange}</p>
      <div class="rating">
        Durability: ${'★'.repeat(tier.durability)}${'☆'.repeat(5 - tier.durability)}
      </div>
      <div class="rating">
        Aesthetics: ${'★'.repeat(tier.aesthetics)}${'☆'.repeat(5 - tier.aesthetics)}
      </div>
      <p class="examples"><strong>Examples:</strong> ${tier.examples.join(', ')}</p>
    </div>
  `).join('')}
  
  <div class="footer">
    <p>Generated by Houspire Material Guide</p>
    <p>www.houspire.com</p>
  </div>
</body>
</html>
`;
        const blob = new Blob([content], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const printWindow = window.open(url, '_blank');
        if (printWindow) {
            printWindow.onload = () => {
                printWindow.print();
            };
        }
        toast({ title: 'PDF Ready', description: 'Print dialog opened for PDF export' });
    };
    const shareViaWhatsApp = () => {
        const tierSummary = category.tiers
            .map(t => `• ${t.name}: ${t.priceRange}`)
            .join('\n');
        const message = `🏠 *${category.name} Material Guide*\n\n${tierSummary}\n\n📊 Compare tiers at:\n${window.location.href}`;
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
        window.open(whatsappUrl, '_blank');
        toast({ title: 'WhatsApp', description: 'Opening WhatsApp share...' });
    };
    const copyLink = () => {
        navigator.clipboard.writeText(window.location.href);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        toast({ title: 'Link Copied', description: 'Page link copied to clipboard' });
    };
    const handleAddToBOQ = () => {
        if (onAddToBOQ) {
            onAddToBOQ(category.id);
            toast({
                title: 'Added to BOQ',
                description: `${category.name} linked to your Bill of Quantities`,
                action: (<Button variant="outline" size="sm" asChild>
            <a href="/boq-viewer">View BOQ</a>
          </Button>)
            });
        }
    };
    const handleSaveFavorite = () => {
        setFavorited(!favorited);
        if (onSaveFavorite) {
            onSaveFavorite(category.id);
        }
        toast({
            title: favorited ? 'Removed from Favorites' : 'Saved to Favorites',
            description: favorited
                ? `${category.name} removed from your favorites`
                : `${category.name} saved to your favorites`
        });
    };
    return (<div className="flex items-center gap-2">
      <Button variant={favorited ? "default" : "outline"} size="sm" onClick={handleSaveFavorite} className="gap-2">
        <Heart className={`h-4 w-4 ${favorited ? 'fill-current' : ''}`}/>
        {favorited ? 'Saved' : 'Save'}
      </Button>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm" className="gap-2">
            <Share2 className="h-4 w-4"/>
            Share
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuItem onClick={generatePDF}>
            <FileText className="h-4 w-4 mr-2"/>
            Download PDF
          </DropdownMenuItem>
          <DropdownMenuItem onClick={shareViaWhatsApp}>
            <MessageCircle className="h-4 w-4 mr-2"/>
            Share via WhatsApp
          </DropdownMenuItem>
          <DropdownMenuItem onClick={copyLink}>
            {copied ? (<Check className="h-4 w-4 mr-2 text-green-500"/>) : (<Link2 className="h-4 w-4 mr-2"/>)}
            {copied ? 'Copied!' : 'Copy Link'}
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={handleAddToBOQ}>
            <ExternalLink className="h-4 w-4 mr-2"/>
            Add to BOQ
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>);
}
