import { format, addWeeks } from 'date-fns';
import { saveAs } from 'file-saver';
import { Calendar, MessageCircle, FileText, Share2, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { useState } from 'react';
export function TimelineExportUtils({ data }) {
    const [copied, setCopied] = useState(false);
    const completionDate = addWeeks(data.startDate, data.totalWeeks);
    const generatePDFContent = () => {
        let cumulativeWeeks = 0;
        const phaseDetails = data.phases.map(phase => {
            const startDate = addWeeks(data.startDate, cumulativeWeeks);
            cumulativeWeeks += phase.weeks;
            const endDate = addWeeks(data.startDate, cumulativeWeeks);
            return `${phase.name}: ${phase.weeks} week(s) | ${format(startDate, 'dd MMM')} - ${format(endDate, 'dd MMM')}\n   ${phase.description}`;
        }).join('\n\n');
        return `
╔════════════════════════════════════════════════════════════════╗
║                    HOUSPIRE TIMELINE ESTIMATE                    ║
╚════════════════════════════════════════════════════════════════╝

PROJECT SUMMARY
═══════════════
Room Type:        ${data.roomName}
Scope:            ${data.scopeName}
Additional Work:  ${data.additions.length > 0 ? data.additions.join(', ') : 'None'}
Buffer Time:      ${data.bufferWeeks} week(s)

TIMELINE OVERVIEW
═════════════════
Start Date:       ${format(data.startDate, 'EEEE, dd MMMM yyyy')}
End Date:         ${format(completionDate, 'EEEE, dd MMMM yyyy')}
Total Duration:   ${data.totalWeeks} weeks

PHASE BREAKDOWN
═══════════════
${phaseDetails}

KEY MILESTONES
══════════════
${data.phases.map((phase, idx) => {
            let weeks = 0;
            for (let i = 0; i <= idx; i++) {
                weeks += data.phases[i].weeks;
            }
            return `✓ ${phase.name} Complete: Week ${weeks} (${format(addWeeks(data.startDate, weeks), 'dd MMM yyyy')})`;
        }).join('\n')}

NOTES
═════
• This is an estimate based on typical project timelines
• Actual duration may vary based on site conditions
• Festive seasons may add 20-30% to execution time
• Pre-ordering materials can speed up procurement

─────────────────────────────────────────────────────────────────
Generated by Houspire | ${format(new Date(), 'dd MMM yyyy')}
www.houspire.com
─────────────────────────────────────────────────────────────────
`.trim();
    };
    const handlePDFDownload = () => {
        const content = generatePDFContent();
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        saveAs(blob, `houspire-timeline-${format(new Date(), 'yyyy-MM-dd')}.txt`);
        toast.success('Timeline downloaded successfully');
    };
    const generateICSContent = () => {
        const events = [];
        let cumulativeWeeks = 0;
        // Add phase events
        data.phases.forEach((phase, idx) => {
            const startDate = addWeeks(data.startDate, cumulativeWeeks);
            cumulativeWeeks += phase.weeks;
            const endDate = addWeeks(data.startDate, cumulativeWeeks);
            events.push(`BEGIN:VEVENT
DTSTART;VALUE=DATE:${format(startDate, 'yyyyMMdd')}
DTEND;VALUE=DATE:${format(endDate, 'yyyyMMdd')}
SUMMARY:${phase.name} - ${data.roomName}
DESCRIPTION:${phase.description}
STATUS:CONFIRMED
END:VEVENT`);
        });
        // Add completion event
        events.push(`BEGIN:VEVENT
DTSTART;VALUE=DATE:${format(completionDate, 'yyyyMMdd')}
DTEND;VALUE=DATE:${format(addWeeks(completionDate, 0), 'yyyyMMdd')}
SUMMARY:🎉 Project Complete - ${data.roomName}
DESCRIPTION:Your ${data.roomName} renovation is complete!
STATUS:CONFIRMED
END:VEVENT`);
        return `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Houspire//Timeline Estimator//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
${events.join('\n')}
END:VCALENDAR`;
    };
    const handleCalendarExport = () => {
        const content = generateICSContent();
        const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
        saveAs(blob, `houspire-timeline-${format(new Date(), 'yyyy-MM-dd')}.ics`);
        toast.success('Calendar events downloaded - import to your calendar app');
    };
    const generateWhatsAppMessage = () => {
        return `🏠 *My ${data.roomName} Timeline*

📅 *Duration:* ${data.totalWeeks} weeks
🗓 *Start:* ${format(data.startDate, 'dd MMM yyyy')}
✅ *Complete:* ${format(completionDate, 'dd MMM yyyy')}

*Phases:*
${data.phases.map(p => `• ${p.name}: ${p.weeks}w`).join('\n')}

_Estimated by Houspire_`;
    };
    const handleWhatsAppShare = () => {
        const message = generateWhatsAppMessage();
        const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
        window.open(url, '_blank');
    };
    const handleCopyLink = async () => {
        try {
            await navigator.clipboard.writeText(window.location.href);
            setCopied(true);
            toast.success('Link copied to clipboard');
            setTimeout(() => setCopied(false), 2000);
        }
        catch {
            toast.error('Failed to copy link');
        }
    };
    const handleNativeShare = async () => {
        if (navigator.share) {
            try {
                await navigator.share({
                    title: `${data.roomName} Timeline - Houspire`,
                    text: `My ${data.roomName} project will take ${data.totalWeeks} weeks!`,
                    url: window.location.href,
                });
            }
            catch {
                // User cancelled
            }
        }
        else {
            handleCopyLink();
        }
    };
    return (<div className="grid grid-cols-2 md:grid-cols-4 gap-3">
      <Button variant="outline" className="flex flex-col items-center gap-1 h-auto py-3" onClick={handlePDFDownload}>
        <FileText className="h-5 w-5"/>
        <span className="text-xs">Download PDF</span>
      </Button>
      
      <Button variant="outline" className="flex flex-col items-center gap-1 h-auto py-3" onClick={handleCalendarExport}>
        <Calendar className="h-5 w-5"/>
        <span className="text-xs">Add to Calendar</span>
      </Button>
      
      <Button variant="outline" className="flex flex-col items-center gap-1 h-auto py-3" onClick={handleWhatsAppShare}>
        <MessageCircle className="h-5 w-5"/>
        <span className="text-xs">WhatsApp</span>
      </Button>
      
      <Button variant="outline" className="flex flex-col items-center gap-1 h-auto py-3" onClick={handleNativeShare}>
        {copied ? <Check className="h-5 w-5 text-emerald-500"/> : <Share2 className="h-5 w-5"/>}
        <span className="text-xs">{copied ? 'Copied!' : 'Share'}</span>
      </Button>
    </div>);
}
